services:
  Movies.controllers.MoviePutController:
    class: ../../../modules/movies/controllers/MoviePutController
    arguments: [ "@Movies.services.MovieCreator" ]

  Movies.controllers.MovieGetController:
    class: ../../../modules/movies/controllers/MovieGetController
    arguments: [ "@Movies.services.MovieFinder" ]

  Movies.services.MovieCreator:
    class: ../../../modules/movies/services/MovieCreator
    arguments: [ "@Movies.repositories.MovieRepository" ]

  Movies.services.MovieCreatorFromTMDB:
    class: ../../../modules/movies/services/MovieCreatorFromTMDB
    arguments: [ "@Movies.repositories.MovieRepository" ]

  Movies.services.MovieFinder:
    class: ../../../modules/movies/services/MovieFinder
    arguments: [ "@Movies.repositories.MovieRepository" ]

  Movies.repositories.MovieRepository:
    class: ../../../modules/movies/persistence/mongoose/MongooseMovieRepository
    arguments: [ '@Shared.ConnectionManager' ]
