imports:
  - { resource: ./shared/application.yaml }
  - { resource: ./status/application.yaml }
  - { resource: ./themoviedatabase/application.yaml }
  - { resource: ./genres/application.yaml }
  - { resource: ./movies/application.yaml }
